
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author AsA
 */
public class AgentGui extends javax.swing.JFrame {

    private static ArrayList<Integer> queens = new ArrayList<>();
    private static ArrayList<String> moves = new ArrayList<>();
    private boolean ready = false;

    /**
     * Creates new form AgentGui
     */
    public AgentGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        F7 = new javax.swing.JLabel();
        F8 = new javax.swing.JLabel();
        F6 = new javax.swing.JLabel();
        F5 = new javax.swing.JLabel();
        F3 = new javax.swing.JLabel();
        F4 = new javax.swing.JLabel();
        F1 = new javax.swing.JLabel();
        F2 = new javax.swing.JLabel();
        G7 = new javax.swing.JLabel();
        E1 = new javax.swing.JLabel();
        E2 = new javax.swing.JLabel();
        E3 = new javax.swing.JLabel();
        E4 = new javax.swing.JLabel();
        E5 = new javax.swing.JLabel();
        E6 = new javax.swing.JLabel();
        E7 = new javax.swing.JLabel();
        E8 = new javax.swing.JLabel();
        G8 = new javax.swing.JLabel();
        G6 = new javax.swing.JLabel();
        G5 = new javax.swing.JLabel();
        G3 = new javax.swing.JLabel();
        G4 = new javax.swing.JLabel();
        G1 = new javax.swing.JLabel();
        G2 = new javax.swing.JLabel();
        H7 = new javax.swing.JLabel();
        H8 = new javax.swing.JLabel();
        H6 = new javax.swing.JLabel();
        H5 = new javax.swing.JLabel();
        H3 = new javax.swing.JLabel();
        H4 = new javax.swing.JLabel();
        H1 = new javax.swing.JLabel();
        H2 = new javax.swing.JLabel();
        A1 = new javax.swing.JLabel();
        A2 = new javax.swing.JLabel();
        A3 = new javax.swing.JLabel();
        A4 = new javax.swing.JLabel();
        A5 = new javax.swing.JLabel();
        A6 = new javax.swing.JLabel();
        A7 = new javax.swing.JLabel();
        A8 = new javax.swing.JLabel();
        B8 = new javax.swing.JLabel();
        B7 = new javax.swing.JLabel();
        B6 = new javax.swing.JLabel();
        B5 = new javax.swing.JLabel();
        B4 = new javax.swing.JLabel();
        B3 = new javax.swing.JLabel();
        B2 = new javax.swing.JLabel();
        B1 = new javax.swing.JLabel();
        C1 = new javax.swing.JLabel();
        C2 = new javax.swing.JLabel();
        C3 = new javax.swing.JLabel();
        C4 = new javax.swing.JLabel();
        C5 = new javax.swing.JLabel();
        C6 = new javax.swing.JLabel();
        C7 = new javax.swing.JLabel();
        C8 = new javax.swing.JLabel();
        D8 = new javax.swing.JLabel();
        D7 = new javax.swing.JLabel();
        D6 = new javax.swing.JLabel();
        D5 = new javax.swing.JLabel();
        D4 = new javax.swing.JLabel();
        D3 = new javax.swing.JLabel();
        D2 = new javax.swing.JLabel();
        D1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        moveList = new javax.swing.JList();
        generate = new javax.swing.JButton();
        solve = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        move = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        reset = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        aNumber = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("8-Queen Agent");
        setMinimumSize(new java.awt.Dimension(915, 570));
        setPreferredSize(new java.awt.Dimension(930, 620));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        F7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/queen.png"))); // NOI18N
        getContentPane().add(F7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 383, -1, -1));

        F8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/queen.png"))); // NOI18N
        getContentPane().add(F8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 383, -1, -1));

        F6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/queen.png"))); // NOI18N
        getContentPane().add(F6, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 383, -1, -1));

        F5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/queen.png"))); // NOI18N
        getContentPane().add(F5, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 383, -1, -1));

        F3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/queen.png"))); // NOI18N
        getContentPane().add(F3, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 383, -1, -1));

        F4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/queen.png"))); // NOI18N
        getContentPane().add(F4, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 383, -1, -1));

        F1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/queen.png"))); // NOI18N
        getContentPane().add(F1, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 383, -1, -1));

        F2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/queen.png"))); // NOI18N
        getContentPane().add(F2, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 383, -1, -1));

        G7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/queen.png"))); // NOI18N
        getContentPane().add(G7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 445, -1, -1));

        E1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/queen.png"))); // NOI18N
        getContentPane().add(E1, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 320, -1, -1));

        E2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/queen.png"))); // NOI18N
        getContentPane().add(E2, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 320, -1, -1));

        E3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/queen.png"))); // NOI18N
        getContentPane().add(E3, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 320, -1, -1));

        E4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/queen.png"))); // NOI18N
        getContentPane().add(E4, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 320, -1, -1));

        E5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/queen.png"))); // NOI18N
        getContentPane().add(E5, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 320, -1, -1));

        E6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/queen.png"))); // NOI18N
        getContentPane().add(E6, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 320, -1, -1));

        E7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/queen.png"))); // NOI18N
        getContentPane().add(E7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, -1, -1));

        E8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/queen.png"))); // NOI18N
        getContentPane().add(E8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 320, -1, -1));

        G8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/queen.png"))); // NOI18N
        getContentPane().add(G8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 445, -1, -1));

        G6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/queen.png"))); // NOI18N
        getContentPane().add(G6, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 445, -1, -1));

        G5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/queen.png"))); // NOI18N
        getContentPane().add(G5, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 445, -1, -1));

        G3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/queen.png"))); // NOI18N
        getContentPane().add(G3, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 445, -1, -1));

        G4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/queen.png"))); // NOI18N
        getContentPane().add(G4, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 445, -1, -1));

        G1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/queen.png"))); // NOI18N
        getContentPane().add(G1, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 445, -1, -1));

        G2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/queen.png"))); // NOI18N
        getContentPane().add(G2, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 445, -1, -1));

        H7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/queen.png"))); // NOI18N
        getContentPane().add(H7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 505, -1, -1));

        H8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/queen.png"))); // NOI18N
        getContentPane().add(H8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 505, -1, -1));

        H6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/queen.png"))); // NOI18N
        getContentPane().add(H6, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 505, -1, -1));

        H5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/queen.png"))); // NOI18N
        getContentPane().add(H5, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 505, -1, -1));

        H3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/queen.png"))); // NOI18N
        getContentPane().add(H3, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 505, -1, -1));

        H4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/queen.png"))); // NOI18N
        getContentPane().add(H4, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 505, -1, -1));

        H1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/queen.png"))); // NOI18N
        getContentPane().add(H1, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 505, -1, -1));

        H2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/queen.png"))); // NOI18N
        getContentPane().add(H2, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 505, -1, -1));

        A1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/queen.png"))); // NOI18N
        getContentPane().add(A1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        A2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/queen.png"))); // NOI18N
        getContentPane().add(A2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        A3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/queen.png"))); // NOI18N
        getContentPane().add(A3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, -1, -1));

        A4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/queen.png"))); // NOI18N
        getContentPane().add(A4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, -1));

        A5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/queen.png"))); // NOI18N
        getContentPane().add(A5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, -1));

        A6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/queen.png"))); // NOI18N
        getContentPane().add(A6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, -1, -1));

        A7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/queen.png"))); // NOI18N
        getContentPane().add(A7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, -1, -1));

        A8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/queen.png"))); // NOI18N
        getContentPane().add(A8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, -1, -1));

        B8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/queen.png"))); // NOI18N
        getContentPane().add(B8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, -1, -1));

        B7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/queen.png"))); // NOI18N
        getContentPane().add(B7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, -1, -1));

        B6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/queen.png"))); // NOI18N
        getContentPane().add(B6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, -1, -1));

        B5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/queen.png"))); // NOI18N
        getContentPane().add(B5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, -1, -1));

        B4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/queen.png"))); // NOI18N
        getContentPane().add(B4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, -1, -1));

        B3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/queen.png"))); // NOI18N
        getContentPane().add(B3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, -1, -1));

        B2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/queen.png"))); // NOI18N
        getContentPane().add(B2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, -1));

        B1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/queen.png"))); // NOI18N
        getContentPane().add(B1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        C1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/queen.png"))); // NOI18N
        getContentPane().add(C1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        C2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/queen.png"))); // NOI18N
        getContentPane().add(C2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, -1));

        C3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/queen.png"))); // NOI18N
        getContentPane().add(C3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, -1, -1));

        C4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/queen.png"))); // NOI18N
        getContentPane().add(C4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, -1));

        C5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/queen.png"))); // NOI18N
        getContentPane().add(C5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, -1, -1));

        C6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/queen.png"))); // NOI18N
        getContentPane().add(C6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, -1, -1));

        C7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/queen.png"))); // NOI18N
        getContentPane().add(C7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, -1, -1));

        C8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/queen.png"))); // NOI18N
        getContentPane().add(C8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, -1, -1));

        D8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/queen.png"))); // NOI18N
        getContentPane().add(D8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, -1, -1));

        D7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/queen.png"))); // NOI18N
        getContentPane().add(D7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, -1, -1));

        D6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/queen.png"))); // NOI18N
        getContentPane().add(D6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, -1, -1));

        D5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/queen.png"))); // NOI18N
        getContentPane().add(D5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, -1, -1));

        D4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/queen.png"))); // NOI18N
        getContentPane().add(D4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, -1, -1));

        D3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/queen.png"))); // NOI18N
        getContentPane().add(D3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, -1, -1));

        D2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/queen.png"))); // NOI18N
        getContentPane().add(D2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, -1, -1));

        D1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/queen.png"))); // NOI18N
        getContentPane().add(D1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chessB.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("8-Queen Agent ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        moveList.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane1.setViewportView(moveList);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 279, 350, 310));

        generate.setText("Generate Problem");
        generate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                generateMousePressed(evt);
            }
        });
        getContentPane().add(generate, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 40, -1, -1));

        solve.setText("Solve");
        solve.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                solveMousePressed(evt);
            }
        });
        getContentPane().add(solve, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Attack Number:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 85, -1, -1));

        move.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        move.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        move.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveActionPerformed(evt);
            }
        });
        getContentPane().add(move, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 80, 60, 30));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, 350, 10));

        reset.setText("Reset");
        reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                resetMousePressed(evt);
            }
        });
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 40, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/queen.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 190, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/queen.png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel6MousePressed(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 130, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/queen.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 190, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/queen.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 190, -1, -1));

        jLabel4.setText("Movements");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("Move Count :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 85, -1, -1));

        aNumber.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(aNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 80, 50, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void moveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moveActionPerformed
/**
 * reset button
 * @param evt 
 */
    private void resetMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetMousePressed
        // TODO add your handling code here:
        ready = false;
        reset(getQueenList());
        moves.removeAll(moves);
        moveList.setListData(moves.toArray());
        move.setText("");
        aNumber.setText("");
    }//GEN-LAST:event_resetMousePressed
/**
 * generate button
 * @param evt 
 */
    private void generateMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generateMousePressed
        // TODO add your handling code here:
        moves.removeAll(moves);
        moveList.setListData(moves.toArray());
        move.setText("");
        Generator g = new Generator();
        queens = g.getRandomQueenPositions();
        moves.add(queens.toString());
        design(queens);
        ready = true;

    }//GEN-LAST:event_generateMousePressed

    /**
     * Solve button
     * @param evt 
     */
    private void solveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_solveMousePressed
        // TODO add your handling code here:
        if (ready) {
            solution(queens);
            design(queens);
        } else {
            JOptionPane.showMessageDialog(null, "You must generate problem first", "Warning!", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_solveMousePressed

    private void jLabel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MousePressed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Istanbul University \n Abdussamed ASLAN \n 1358110066", "Admin!", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jLabel6MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgentGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgentGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgentGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgentGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AgentGui().setVisible(true);
            reset(getQueenList());
            Generator g = new Generator();
            AttackCalculator a = new AttackCalculator();
            moveList.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent evt) {
                    if (evt.getClickCount() == 2) {
                        queens = moveListToQueens(moveList.getSelectedValue().toString());
                        aNumber.setText(a.getAttackNumber(g.createChessBoard(queens), queens)+"");
                        design(queens);
                    }
                }
            });
        });
    }

    public static ArrayList<Integer> moveListToQueens(String s) {
        String c;
        ArrayList<Integer> temp = new ArrayList<>();
        for (int i = 1; i < 23; i = i + 3) {
            temp.add(Integer.parseInt(s.substring(i, i + 1)));
        }
        return temp;
    }

    /**
     * queen visible setting
     * @param jl 
     */
    public static void reset(ArrayList<JLabel> jl) {

        for (JLabel j : jl) {
            j.setVisible(false);
        }
    }

    /**
     * This metod designs chess board for GUI
     * @param queens 
     */
    public static void design(ArrayList<Integer> queens) {
        Generator g = new Generator();
        reset(getQueenList());
        int count = 0;
        for (int i = 0; i < 8; i++) {
            for (int j = 0; j < 8; j++) {
                if (g.createChessBoard(queens)[i][j] == 1) {
                    getQueenList().get(count).setVisible(true);
                }
                count++;

            }
        }
    }

    /**
     * This metod brain of agent, its solves 8-queen problems
     * @param queens 
     */
    public static void solution(ArrayList<Integer> queens) {
        Generator g = new Generator();
        AttackCalculator a = new AttackCalculator();
        Movements m = new Movements();
        int h = a.getAttackNumber(g.createChessBoard(queens), queens);
        int[][] attacks;
        int min;
        int counter = 0;
        while (h != 0) {
            if (counter > 40320) {
                JOptionPane.showMessageDialog(null, "Solution Not Found", "Warning!", JOptionPane.INFORMATION_MESSAGE);
                break;
            }
            attacks = a.findAllPosibleAttacks(queens);
            min = m.findMinValue(attacks);
            ArrayList<String> movements = m.getPosibleMovements(attacks, min);
            queens = m.generateNewQueens(m.pickQueenMovement(movements), queens);
            h = a.getAttackNumber(g.createChessBoard(queens), queens);
            moves.add(queens.toString());
            counter++;
        }
        aNumber.setText(h+"");
        move.setText(counter + "");
        moveList.setListData(moves.toArray());
    }

    // Queens
    public static ArrayList<JLabel> getQueenList() {
        ArrayList<JLabel> lb;
        lb = new ArrayList<>();
        lb.add(A1);
        lb.add(A2);
        lb.add(A3);
        lb.add(A4);
        lb.add(A5);
        lb.add(A6);
        lb.add(A7);
        lb.add(A8);
        lb.add(B1);
        lb.add(B2);
        lb.add(B3);
        lb.add(B4);
        lb.add(B5);
        lb.add(B6);
        lb.add(B7);
        lb.add(B8);
        lb.add(C1);
        lb.add(C2);
        lb.add(C3);
        lb.add(C4);
        lb.add(C5);
        lb.add(C6);
        lb.add(C7);
        lb.add(C8);
        lb.add(D1);
        lb.add(D2);
        lb.add(D3);
        lb.add(D4);
        lb.add(D5);
        lb.add(D6);
        lb.add(D7);
        lb.add(D8);
        lb.add(E1);
        lb.add(E2);
        lb.add(E3);
        lb.add(E4);
        lb.add(E5);
        lb.add(E6);
        lb.add(E7);
        lb.add(E8);
        lb.add(F1);
        lb.add(F2);
        lb.add(F3);
        lb.add(F4);
        lb.add(F5);
        lb.add(F6);
        lb.add(F7);
        lb.add(F8);
        lb.add(G1);
        lb.add(G2);
        lb.add(G3);
        lb.add(G4);
        lb.add(G5);
        lb.add(G6);
        lb.add(G7);
        lb.add(G8);
        lb.add(H1);
        lb.add(H2);
        lb.add(H3);
        lb.add(H4);
        lb.add(H5);
        lb.add(H6);
        lb.add(H7);
        lb.add(H8);
        return lb;

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JLabel A1;
    private static javax.swing.JLabel A2;
    private static javax.swing.JLabel A3;
    private static javax.swing.JLabel A4;
    private static javax.swing.JLabel A5;
    private static javax.swing.JLabel A6;
    private static javax.swing.JLabel A7;
    private static javax.swing.JLabel A8;
    private static javax.swing.JLabel B1;
    private static javax.swing.JLabel B2;
    private static javax.swing.JLabel B3;
    private static javax.swing.JLabel B4;
    private static javax.swing.JLabel B5;
    private static javax.swing.JLabel B6;
    private static javax.swing.JLabel B7;
    private static javax.swing.JLabel B8;
    private static javax.swing.JLabel C1;
    private static javax.swing.JLabel C2;
    private static javax.swing.JLabel C3;
    private static javax.swing.JLabel C4;
    private static javax.swing.JLabel C5;
    private static javax.swing.JLabel C6;
    private static javax.swing.JLabel C7;
    private static javax.swing.JLabel C8;
    private static javax.swing.JLabel D1;
    private static javax.swing.JLabel D2;
    private static javax.swing.JLabel D3;
    private static javax.swing.JLabel D4;
    private static javax.swing.JLabel D5;
    private static javax.swing.JLabel D6;
    private static javax.swing.JLabel D7;
    private static javax.swing.JLabel D8;
    private static javax.swing.JLabel E1;
    private static javax.swing.JLabel E2;
    private static javax.swing.JLabel E3;
    private static javax.swing.JLabel E4;
    private static javax.swing.JLabel E5;
    private static javax.swing.JLabel E6;
    private static javax.swing.JLabel E7;
    private static javax.swing.JLabel E8;
    private static javax.swing.JLabel F1;
    private static javax.swing.JLabel F2;
    private static javax.swing.JLabel F3;
    private static javax.swing.JLabel F4;
    private static javax.swing.JLabel F5;
    private static javax.swing.JLabel F6;
    private static javax.swing.JLabel F7;
    private static javax.swing.JLabel F8;
    private static javax.swing.JLabel G1;
    private static javax.swing.JLabel G2;
    private static javax.swing.JLabel G3;
    private static javax.swing.JLabel G4;
    private static javax.swing.JLabel G5;
    private static javax.swing.JLabel G6;
    private static javax.swing.JLabel G7;
    private static javax.swing.JLabel G8;
    private static javax.swing.JLabel H1;
    private static javax.swing.JLabel H2;
    private static javax.swing.JLabel H3;
    private static javax.swing.JLabel H4;
    private static javax.swing.JLabel H5;
    private static javax.swing.JLabel H6;
    private static javax.swing.JLabel H7;
    private static javax.swing.JLabel H8;
    private static javax.swing.JTextField aNumber;
    private javax.swing.JButton generate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private static javax.swing.JTextField move;
    private static javax.swing.JList moveList;
    private javax.swing.JButton reset;
    private javax.swing.JButton solve;
    // End of variables declaration//GEN-END:variables
}
